### ISSUE TITLE
Header has a light background color

### ISSUE THREAD

**Issue by cosmadora** [lazaroblanc/icingaweb2-dark-theme#1]
Hi, 

the `<div id="header">` seems to have a weird light background color and doesnt fit into the rest of the color scheme:

![image](https://user-images.githubusercontent.com/6391042/141150037-3c4a8058-c424-4907-8108-41ad11f4bfe5.png)

Tested in Firefox 94.0.1 and Chrome 95.0.4638.69

You could probably fix that with 
```css
#header {
    background-color: transparent;
}
```

Best regards, 

Laura
